# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-29 21:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_reg_form', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='extrainfo',
            name='employment_status',
            field=models.CharField(blank=True, choices=[(b'efw', b'Employed for wages'), (b'selfemployed', b'Self-employed'), (b'student', b'Student'), (b'homemaker', b'Homemaker'), (b'oowlfw', b'Out of work and looking for work'), (b'oownclfw', b'Out of work but not currently looking for work'), (b'military', b'Military'), (b'retired', b'Retired'), (b'utw', b'Unable to work'), (b'other', b'Other')], db_index=True, max_length=20, null=True),
        ),
    ]
