# Generated by Django 2.2.15 on 2020-09-17 21:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('custom_reg_form', '0002_auto_20200917_2114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extrainfo',
            name='email',
        ),
        migrations.RemoveField(
            model_name='extrainfo',
            name='user',
        ),
        migrations.AddField(
            model_name='extrainfo',
            name='emailID',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+email+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='extrainfo',
            name='userID',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+user+', to=settings.AUTH_USER_MODEL),
        ),
    ]
