# Generated by Django 2.2.15 on 2020-09-17 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_reg_form', '0003_auto_20200917_2130'),
    ]

    operations = [
        migrations.RenameField(
            model_name='extrainfo',
            old_name='emailID',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='extrainfo',
            old_name='userID',
            new_name='user',
        ),
    ]
