# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-09-16 09:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_reg_form', '0003_auto_20200916_0856'),
    ]

    operations = [
        migrations.AddField(
            model_name='extrainfo',
            name='email_gdpr_consent',
            field=models.BooleanField(db_index=True, default=False, verbose_name=b'Subscribe me to the newsletter from NTNU Videre'),
        ),
        migrations.AlterField(
            model_name='extrainfo',
            name='user',
            field=models.BooleanField(default=True, verbose_name='auth.User'),
        ),
    ]
