# Generated by Django 2.2.15 on 2020-09-18 05:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('custom_reg_form', '0004_auto_20200917_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extrainfo',
            name='email',
            field=models.EmailField(max_length=254, null=True, verbose_name='auth.User'),
        ),
        migrations.AlterField(
            model_name='extrainfo',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='++ExtraInfo.user++', to=settings.AUTH_USER_MODEL),
        ),
    ]
