# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-09-17 13:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('custom_reg_form', '0004_auto_20200916_0950'),
    ]

    operations = [
        migrations.AddField(
            model_name='extrainfo',
            name='andreas',
            field=models.BooleanField(db_index=True, default=None, verbose_name=b'Subscribe me to the newsletter from NTNU Videre'),
        ),
        migrations.AlterField(
            model_name='extrainfo',
            name='email_gdpr_consent',
            field=models.BooleanField(db_index=True, default=None, verbose_name=b'Subscribe to NTNU Beta'),
        ),
        migrations.AlterField(
            model_name='extrainfo',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
