# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-10-02 10:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('custom_reg_form', '0005_auto_20200917_1325'),
    ]

    operations = [
        migrations.AddField(
            model_name='extrainfo',
            name='email',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='extrainfo',
            name='email_gdpr_consent',
            field=models.BooleanField(db_index=True, default=True, verbose_name=b'Subscribe to NTNU Beta'),
        ),
    ]
