# Generated by Django 2.2.15 on 2020-09-18 06:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('custom_reg_form', '0006_auto_20200918_0545'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extrainfo',
            name='email',
        ),
        migrations.AddField(
            model_name='extrainfo',
            name='email',
            field=models.ManyToManyField(null=True, related_name='_extrainfo_email_+', related_query_name='User.email', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='extrainfo',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+ExtraInfo.user +', to=settings.AUTH_USER_MODEL),
        ),
    ]
