# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-10-02 10:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('custom_reg_form', '0006_auto_20201002_1027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extrainfo',
            name='email',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='email+', to=settings.AUTH_USER_MODEL),
        ),
    ]
