# Generated by Django 2.2.15 on 2020-09-18 09:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('custom_reg_form', '0009_auto_20200918_0826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extrainfo',
            name='email',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='email+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='extrainfo',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user+', to=settings.AUTH_USER_MODEL),
        ),
    ]
